#
# Module manifest for module 'ConvertFrom-JsonToHashtable'
#
# Generated by: abgox
#
# Generated on: 2024/5/16
#

@{

    RootModule        = 'ConvertFrom-JsonToHashtable.psm1'

    ModuleVersion     = '0.1.1'

    GUID              = '9aa690d8-6804-43a8-b08c-ede290dd9ee9'

    Author            = 'abgox'

    Copyright         = '(c) abgox. All rights reserved.'

    Description       = 'The ConvertFrom-Json method does not have the -AsHashtable switch in Windows PowerShell, which makes it inconvenient to convert json to hashtable.
 This module is used to solve this problem.
 For more information, please visit the project:
  - Github:  https://github.com/abgox/ConvertFrom-JsonToHashtable
  - Gitee:   https://gitee.com/abgox/ConvertFrom-JsonToHashtable
 '

    PowerShellVersion = '5.0'

    FunctionsToExport = 'ConvertFrom-JsonToHashtable'

    PrivateData       = @{

        PSData = @{

            Tags       = @('PowerShell', 'json', 'ConvertFrom-Json' , 'ConvertFrom-JsonToHashtable')

            LicenseUri = 'https://github.com/abgox/ConvertFrom-JsonToHashtable/blob/main/LICENSE'

            ProjectUri = 'https://github.com/abgox/ConvertFrom-JsonToHashtable'

        }

    }
}
