name: Publish to PowerShell Gallery

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate module manifest
        run: |
          $manifestPath = "./module/ConvertFrom-JsonAsHashtable/ConvertFrom-JsonAsHashtable.psd1"
          Test-ModuleManifest -Path $manifestPath
          Write-Output "Module manifest validation passed"

      - name: Publish to Gallery
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          $publishParams = @{
            Path        = "./module/ConvertFrom-JsonAsHashtable"
            NuGetApiKey = $env:PSGALLERY_API_KEY
            ErrorAction = 'Stop'
          }
          Publish-Module @publishParams
          Write-Output "Published to PowerShell Gallery successfully"
